---
jdg_version: "8.2.0"
jdg_default_installation_path: "/opt/redhat-datagrid-{{ jdg_version }}-server/"
jdg_healthcheck: yes
jdg:
  home: "{{ override_jdg_home | default(jdg_default_installation_path) }}"
  bind_addr: "{{ override_jdg_bind_addr | default('localhost') }}"
  port: "{{ override_jdg_port | default('11222') }}"
  config:
    name: "{{ override_jdg_config | default('jdg.xml') }}"
    template: "{{ override_jdg_config_template | default('templates/infinispan.xml.j2') }}"
    users: "{{ override_jdg_config_users_properties | default('users.properties') }}"
    groups: "{{ override_jdg_config_group_properties | default('groups.properties') }}"
  user:
    name: "{{ override_jdg_user | default('jdg') }}"
  group:
    name: "{{ override_jdg_group | default('jdg') }}"
  service:
    name: "{{ override_jdg_service_name | default('jdg') }}"
  users:
    - { name: 'rpelisse', password: 'itsme', roles: 'supervisor' }

jdg_keycloak_cache:
  enabled: True
  caches:
    - sessions
    - offlineSessions
    - clientSessions
    - offlineClientSessions
    - loginFailures
    - actionTokens
