---
- set_fact:
    wildfly_instance_management_port: "{{ 9990 + ((item - wildfly.port_range_offset) * 100) }}"
    wildfly_instance_http_port: "{{ 8080 + ((item - wildfly.port_range_offset) * 100) }}"
    wildfly_instance_https_port: "{{ 8443 + ((item - wildfly.port_range_offset) * 100) }}"

- name: configure firewall for Wildfly ports
  become: yes
  firewalld:
    port: "{{ port }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "{{ wildfly_instance_http_port }}/tcp"
    - "{{ wildfly_instance_https_port }}/tcp"
  loop_control:
    loop_var: port

- name: Set application detail
  set_fact:
    app_detail: "{{ apps | selectattr('version','equalto', sample_app_version) | list | first }}"

- name: Set Application Destination Directory
  set_fact:
    app_dest: "{{ app_dir + '/' + app_detail.name + '-' + app_detail.version + '.' + app_detail.extension }}"

- stat:
    path: "{{ app_dest }}"
  register: app_dest_path

- name: "Download a demo app to deploy"
  get_url:
    url: "{{ app_detail.url }}"
    dest: "{{ app_dest }}"
  when:
    - app_dest_path is defined
    - app_dest_path.stat is defined
    - not app_dest_path.stat.exists


- name: "Download a info app to deploy"
  get_url:
    url: "http://people.redhat.com/~rpelisse/info-1.1.war"
    dest: "/opt/info-1.1.war"
  when:
    - info_app is defined

- name: Get keycloak auth token
  uri:
    url: "{{ keycloak_url }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id={{ keycloak_auth_client }}&username={{ keycloak_admin_user }}&password={{ keycloak_admin_password }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  until: keycloak_auth_response.status == 200
  retries: 5
  delay: 2
  run_once: true

- name: "Get Clients"
  uri:
    url: "{{ keycloak_url }}/auth/admin/realms/{{ keycloak_realm }}/clients"
    method: GET
    status_code:
     - 200
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
  register: keycloak_client_response

- name: "Get Client Secret"
  uri:
    url: "{{ keycloak_url }}/auth/admin/realms/{{ keycloak_realm }}/clients/{{ (keycloak_client_response.json | selectattr('clientId', 'equalto', keycloak_client) | list | first).id }}/client-secret"
    method: GET
    status_code:
     - 200
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
  register: keycloak_client_secret_response

- name: "Fine tune Wildfly configuration"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    rule_file: /etc/jcliff/
    timeout: 7000
    management_port: "{{ wildfly_instance_management_port }}"
    components:
      - system_properties:
        - name: JBOSS_ID
          value: "{{ wildfly.basedir_prefix }}{{ item }}"
      - deployments:
          - name: "{{ app_dest | basename }}"
            path: "{{ app_dest }}"
            replace_runtime_name_regex: "{{  (app_dest | basename).split('-')[0] }}-.*"
          - name: info-1.0.war
            path: /opt/info-1.0.war
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - datasources:
          - name: "{{ wildfly.config_name_prefix }}db"
            use_java_context: 'true'
            jndi_name: "java:jboss/datasources/{{ postgres.db_name }}"
            connection_url: "jdbc:postgresql://localhost:5432/{{ postgres.db_name }}"
            driver_name: postgresql
            user_name: "{{ postgres.user.name }}"
            password: "{{ postgres.user.password }}"
      - keycloak:
          - secure_deployment:
              - deployment_name: "{{ app_detail.name + '.' + app_detail.extension }}"
                realm: "{{ keycloak_realm }}"
                auth_server_url: "{{ keycloak_url }}/auth/"
                ssl_required: EXTERNAL
                resource: "{{ keycloak_client }}"
                credential: "{{ keycloak_client_secret_response.json.value }}"
                verify_token_audience: true
                use_resource_role_mappings: true
      - modcluster:
          proxy:
            - name: default
              proxies:
                - proxy1
- debug:
    msg: "nb_instance_by_node: {{ nb_instances }}"
