---
- name: "Ensures JCliff version is appropriate"
  yum:
    name: jcliff-2.12.8
    state: present

- name: "Fine tuning configuration: {{ instance_name | default('localhost') }}"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    rule_file: roles/3trains_wildfly/files/custom/
    timeout: 7000
    management_port: "{{ wildfly_instance_management_port }}"
    components:
      - system_properties:
          - name: JBOSS_ID
            value: "{{ instance_name }}"
      - deployments:
          - name: "{{ demo_app_dest | basename }}"
            path: "{{ demo_app_dest }}"
            replace_runtime_name_regex: "{{ (demo_app_dest | basename).split('-')[0] }}-.*"
          - name: "{{ info_app_dest | basename }}"
            path: "{{ info_app_dest }}"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - datasources:
          - name: "{{ instance_name }}db"
            use_java_context: 'true'
            jndi_name: "java:jboss/datasources/{{ postgres.db_name }}"
            connection_url: "jdbc:postgresql://{{ (groups['pgsql'][0] if groups['pgsql'] | length > 0 else 'localhost') }}:5432/{{ postgres.db_name }}"
            driver_name: postgresql
            user_name: "{{ postgres.user.name }}"
            password: "{{ postgres.user.password }}"
      - keycloak:
          - secure_deployment:
              - deployment_name: "{{ secure_deployment_name }}"
                realm: "{{ keycloak_realm }}"
                auth_server_url: "{{ keycloak_redirect_url }}/auth/"
                ssl_required: EXTERNAL
                resource: "{{ keycloak_client }}"
                credential: "{{ keycloak_client_secret_response.json.value | default(omit) }}"
                verify_token_audience: true
                use_resource_role_mappings: true
                disable_trust_manager: "{{ keycloak_disable_trust_manager | default(false) }}"
      - modcluster:
          proxy:
            - name: default
              proxies:
                - proxy1
  environment:
    JAVA_HOME: "{{ java.home }}"
