---
- assert:
    that:
      - wildfly is defined
      - wildfly.home is defined
      - keycloak_download_url is defined
    quiet: true

- name: Download Keycloak Adapter
  unarchive:
    src: "{{ keycloak_download_url }}"
    dest: "{{ wildfly.home }}"
    remote_src: yes
    creates: "{{ wildfly.home }}/modules/system/add-ons/keycloak"
  notify:
