---
sample_app_version: "{{ sample_app_version_to_deploy | default('0.0.1') }}"
apps:
  - name: kitchensink
    extension: war
    version: "0.0.1"
    url: "https://drive.google.com/uc?export=download&id=1PfTn2zk-UVbLoPDT-xf9Z4AdkNaEfTh3"
  - name: kitchensink
    extension: war
    version: "0.0.2"
    url: "https://drive.google.com/uc?export=download&id=1nrKPe6N7aDwilz6YIzImw1PznaYHuEDj"
app_dir: /tmp
wfly_version: 19.0.0.Final
workdir: /opt/wildfly/
wfly_zipfile: "wildfly-{{ wfly_version }}.zip"
wfly_download_url: https://download.jboss.org/wildfly/{{ wfly_version }}/{{ wfly_zipfile }}
keycloak_adapter_version: 9.0.3
keyclodk_download_url: https://downloads.jboss.org/keycloak/{{ keycloak_adapter_version }}/adapters/keycloak-oidc/keycloak-wildfly-adapter-dist-{{ keycloak_adapter_version }}.tar.gz
java:
  home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/
wildfly:
  home: "{{ workdir }}/wildfly-{{ wfly_version }}/"
  user: wildfly
  group: wildfly
  bind_addr: "{{ override_wildfly_bind_addr | default('0.0.0.0') }}"
  private_addr: "{{ override_wildfly_bind_addr | default(ansible_all_ipv4_addresses) }}"
  port_range_offset: 0
  base_config: standalone-ha.xml
  config_name_prefix: wfly-
  basedir_prefix: /var/run/wfly-
  min_mem: 64m
  max_mem: 512m
  metaspace_size: 96m
  metaspace_maxsize: 256m
postgres:
  db_name: wildfly
  user:
    name: wildfly
    password: wildfly
# can't use a structure for the jdbc_driver because of the interpolation between variables.
jdbc_driver_module_dir: "{{ wildfly.home }}//modules/org/postgresql/main"
jdbc_driver_version: 9.2-1002-jdbc4
jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
ansible_distribution: Fedora
jcliff_rules_dir: /usr/share/jcliff/rules
keycloak_auth_client: admin-cli
keycloak_admin_user: admin
keycloak_admin_password: "redhat1!"
keycloak_realm: 3trains
keycloak_url: "{{ keycloak_3trains_url | default('http://localhost:8080') }}"
keycloak_client: 3trains
